.pragma library

/*
  This file has been automatically generated by the script 'create_icons_js_singleton.sh'.
*/

var prefix = "qrc:/assets/icons/tabler"

var MOON = Qt.resolvedUrl(prefix+"/moon.svg")
var SUN = Qt.resolvedUrl(prefix+"/sun.svg")
