#/*
# *
# *  Copyright 2023 Leonardo Tarollo (LTDev) <develtar@gmail.com>
# *
# *  Licensed under the Apache License, Version 2.0 (the "License");
# *  you may not use this file except in compliance with the License.
# *  You may obtain a copy of the License at
# *
# *      http://www.apache.org/licenses/LICENSE-2.0
# *
# *  Unless required by applicable law or agreed to in writing, software
# *  distributed under the License is distributed on an "AS IS" BASIS,
# *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# *  See the License for the specific language governing permissions and
# *  limitations under the License.
# *
# */

#!/bin/bash 
SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

# Usage: bash create_icons_js_resource.sh ./tabler ./tabler qrc:/assets/icons/tabler

if [ ! $# -eq 3 ]; then
    echo "Usage: bash ${SCRIPT_NAME} <source-folder> <js-destination-folder> <assets-icons-uri->"
    echo "eg."
    echo "     bash ${SCRIPT_NAME} tabler . qrc://assets/icons"
    exit 1
fi

# The path where icons are located
SRC_FOLDER="$1"

# The path where icons must be saved
DST_FOLDER="$2"

# The absolute path where icons will be stored
ICONS_URI="$3"


mkdir $DST_FOLDER

start_time="$(date -u +%s)"

JS_FILE="$DST_FOLDER/icons.js"

echo ".pragma library" > $JS_FILE
echo "" >> $JS_FILE
echo "/*" >> $JS_FILE
echo "  This file has been automatically generated by the script '$SCRIPT_NAME'." >> $JS_FILE
echo "*/" >> $JS_FILE
echo "" >> $JS_FILE
echo "var prefix = \"$ICONS_URI\"" >> $JS_FILE
echo "" >> $JS_FILE

# Resize all images 
for f in "$SRC_FOLDER"/*.svg; do
    # Retrieve file name
    ICON="${f##*/}"
    ICON_NAME="${ICON%.*}"

    # Compress svgs
    #svgo "$f" -o "$DST_FOLDER/$ICON"
    #echo "$f  -->  $DST_FOLDER/$ICON"
    #sync
    
    # Trim and Strip spaces
    ICON_TAG=$(echo $ICON_NAME | tr -s ' ' | sed 's/ *$//g')

    # Replace spaces and minus character with underscore
    ICON_TAG="${ICON_TAG// /_}"
    ICON_TAG="${ICON_TAG//-/_}"

    # Upper case tag
    ICON_TAG="${ICON_TAG^^}"
    echo "var $ICON_TAG = Qt.resolvedUrl(prefix+\"/$ICON\")" >> $JS_FILE
    
done

end_time="$(date -u +%s)"
tot_elapsed="$(($end_time-$start_time))"
echo "Operation completed. $tot_elapsed seconds elapsed."

exit 0
